#:schema node_modules/wrangler/config-schema.json
name = "seller-erp"
compatibility_date = "2024-05-12"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "apps/web/.vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "seller-erp-db"
database_id = "7d79d1ce-099a-4339-8b27-c0acfa692090"
migrations_dir = "packages/db/d1-migrations"
